#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other compliant shell available, you may
#     specify it by using SHELL=/bin/other_shell_name in the environment,
#     or can set "GRADLE_SHELL" environment variable to use a different shell.
# (2) The Java home directory must be set to point to the correct JDK.
#     It can be set in the individual profile files in ~/.gradle/gradle.properties,
#     but it can be set globally in /etc/profile, /etc/bash.bashrc, and others.
# (3) You may need to set GRADLE_OPTS to some reasonable value, e.g.
#     GRADLE_OPTS="-Xmx64m"
# (4) For MSYS or Cygwin, switch paths to Windows-style, e.g. -Xmx1024m
#     becomes -Xmx1024m (Windows interfaces can't handle backslashes)
# (5) The GRADLE_SKIPPING environment variable can be set to "true" or "false"
#     If not set, it will be skipped if either -q flag is set, TERM variable is
#     not set, or the system is not interactive.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME="${app_path%"${app_path##*/}"}"
    [ -n "$APP_HOME" ] && APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) || break
    app_path="${1:+$APP_HOME}${1##*/}"
done

APP_HOME=$(cd "${APP_HOME:-.}" 2>/dev/null && pwd) || exit 1

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

# Use the maximum available, or use the default.
if [ "$GRADLE_HEAPSIZE" = "" ]; then
  HEAP_OPT="-Xmx64m"
else
  HEAP_OPT="-Xmx${GRADLE_HEAPSIZE}m"
fi

if [ "$GRADLE_HEAPSIZE_MIN" = "" ]; then
  HEAP_MIN_OPT="-Xms64m"
else
  HEAP_MIN_OPT="-Xms${GRADLE_HEAPSIZE_MIN}m"
fi

# Use the maximum available, or use the default.
if [ "$GRADLE_HEAPSIZE" != "" ]; then
  GRADLE_OPTS="$GRADLE_OPTS -Xmx${GRADLE_HEAPSIZE}m"
fi
if [ "$GRADLE_HEAPSIZE_MIN" != "" ]; then
  GRADLE_OPTS="$GRADLE_OPTS -Xms${GRADLE_HEAPSIZE_MIN}m"
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "Error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        exit 1
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
    case $uname in
        'Linux')
            ulimit -n 1048576
            ;;
        'Darwin')
            ulimit -n 200000
            ;;
    esac
fi

# For Cygwin or MSYS, switch paths to Windows-style
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;; # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like absolute file path #(
                    [ -e "$t" ] )) # edge case: might be empty
            then
                arg=$( cygpath --path --unix "$arg" )
            ;;
        esac
    done
fi


# Collect all arguments for the java command;
# * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#   shell script including quotes and variable substitutions, so put them in
#   double quotes to make sure that they get re-expanded; and
# * put everything else in single quotes, so that the *nix shell doesn't do any
#   expansion of such variables in the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has processed all arguments;
# the last arg is reserved for the bash exit code.
rest()
{
    while
        arg=$1
        shift
        # there's a test between every parse, so || must be last
        [ "$arg" != '--args' ]
    do
        args=$args\ $(
            printf '%s\n' "$arg" |
            sed "s/'/'\\\\&'/g;s/^/'/;s/$/'/"
        ) # end printf
    done
    echo "$args"
}
parse_args()
{
    args=""
    while
        arg=$1
        shift
        case "$arg" in #(
          --)   # end of options
                shift
                break ;;
          -*)   # options
                args=$args\ $(
                    printf '%s\n' "$arg" |
                    sed "s/'/'\\\\&'/g;s/^/'/;s/$/'/"
                ) # end printf
                ;;
          *)    # operand
                break ;;
        esac
    done
    echo "$args"
}
eval "set -- $(parse_args \"$@\")" '"$@"'
rest
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

